### ISSUE TITLE
Retire the comment sections after each story

### ISSUE THREAD

**Issue by haakenlid** [universitas/universitas.no#147]
Let's retire the comments section.

- [x] Make comment section opt-in. Just change the default value from `facebook` to `None` in the django field.
- [ ] After a while, we can close and just remove the comment section for already published contents. I doubt most readers would notice if we just did this over night, but there might be some trolls complaining. So, like most design/UX changes, it's better to be a sneaky about it.

**Comment by evanbo** [comment]
This is done
