### ISSUE TITLE
Legge til styreside

### ISSUE THREAD

**Issue by siljosaurus** [universitas/universitas.no#168]
Vi ønsker å legge til en ny side med informasjon om styret.

**Comment by evanbo** [comment]
Vi fikk til å lage en ny side, StyreInfo, (og lage en lenke til en side i AboutUniversitas.js), men vi er litt usikre på dette med routing. Vi fikk også til å lage en const toStyret() i router.js, men vi er litt usikre på hva vi må gjøre ellers for å koble sammen de endringene i router.js, med den siden vi har laget, slik at lenken faktisk fungerer

**Comment by evanbo** [comment]
Vi klarte å løse problemet!
