### ISSUE TITLE
interaktivt innhold

### ISSUE THREAD

**Issue by haakenlid** [universitas/universitas.no#19]
Hva slags interaktivt innhold kan vi ønske oss i nettavisa? Først finner vi noen eksempler på andre nettsider på ting som vi kunne tenke oss å ha på plass, deretter finner vi ut hvordan det kan implementeres. 

D3js er et javascript-bibliotek for interaktiv grafikk i nettleseren. Man kan gjøre utrolig mye med det, men det er mye å sette seg inn i. Siden nyhetsgrafikk er redaksjonelt innhold er det nødvendig at noen i redaksjonen har kompetanse på å bruke verktøyene.

Hjemmeside for d3js:
http://d3js.org/

Nvd3: en samling med graf-maler for d3js som er gjenbrukbare.
http://nvd3.org/examples/index.html

En django-app for å integrere nvd3 med Django.
https://github.com/areski/django-nvd3

**Comment by Haakenlid** [comment]
Denne er litt nedprioritert inntil videre. 

d3.js virker veldig lovende - hovedutvikler Mike Bostock jobber i NY Times og har laget mange veldig bra visualiseringer med dette. https://github.com/mbostock/d3

Kart fra midterms høsten 2014 visualisert med d3.
http://www.nytimes.com/interactive/2014/11/04/upshot/senate-maps.html
