### ISSUE TITLE
Relaterte saker i artikkelvisning

### ISSUE THREAD

**Issue by haakenlid** [universitas/universitas.no#21]
På slutten av artikler skal det være lenker videre til relaterte saker som kan velges av nettredaktør eller generes automatisk basert på lignende nøkkelord.

**Comment by Haakenlid** [comment]
Legg inn som m2m i Story.

I utgangspunktet så kan det være en veldig enkel algoritme som finner relaterte saker ut fra dato, seksjon og temaord.

På lengre sikt kan man lage noe mer avasert som tar utgangpunkt i innholdet i teksten i tillegg til de andre faktorene.

**Comment by Velmont** [comment]
Elasticsearch er forresten òg relativt flink til å finna relaterte saker.
Ikkje like godt som ein manuell m2m då.

Har de eit konsept om "følgjesaker"? Typ når noko blir stort og viktig,
t.d. idiotien til ILN ved språksamlingane og Norsk Ordbok 2014,  og det er
fleire artiklar om det, slikt er ofte fint å kopla saman til ein
«Nedleggjing av språksamlingane», med alle artiklane i serien kopla opp.
Har sett det i bruk andre stader iallfall. Vil tru det er ein meir
spesifikk versjon av relaterte artiklar - kanhenda meir brukbar. Relaterte
artiklar som eigentleg ikkje er so relevante kan fort verta litt støyute.

**Comment by Haakenlid** [comment]
Det er ikke noe veldig gjennomført opplegg for følgesaker, men det nærmeste er temaord. For eksempel "Rektorvalg 2014" – som kan brukes som tema både i nyhet og debatt. Men det er veldig halvveis implementert i arkivet sålangt. På nett har temaordene ofte blitt droppet, selv om de fantes på trykk.

Det går nok an å endre praksisen framover, og heller la saker i arkivet få stå uten temaord.

Jeg tenker at det mest nyttige er å lage en del koblinger automatisk, og så kan redaksjonen eventuelt endre eller legge til andre koblinger manuelt. Vet du hvordan elasticsearch finner ut av relaterte saker?

**Comment by Velmont** [comment]
Nei, eg las dokumentasjonen for noko anna, og såg referansar til det. Fekk
òg med meg at det vart ein god del brukt i ein artikkel om elasticsearch
til meir enn søk. :) Same kva, det var berre meint som eit apropos.
