### ISSUE TITLE
System for å slå sammen to eller flere model-instances til en.

### ISSUE THREAD

**Issue by haakenlid** [universitas/universitas.no#31]
Feilstavede bylines fører til at det er mange ekstra bidragsytere i databasen.
For å slå sammen to objekter, må man sørge for at databaserelasjoner til andre tabeller blir slått sammen også.

Det samme gjelder ImageFile-objekter som viser til en og samme bildefil.

**Comment by Haakenlid** [comment]
Denne er relevant for #48 - det er en del klonede saker i databasen.

**Comment by haakenlid** [comment]
På plass!
