### ISSUE TITLE
Generell listevisning django template tag

### ISSUE THREAD

**Issue by haakenlid** [universitas/universitas.no#37]
Lage en template tag for standard visning av en kort liste med artikler. Dette kan brukes mange steder på siden: søkeresultat, "mest lest", "relaterte saker" - osv.

Tag kan se slik ut
`{% story_list stories 5 100 100 %}`

Funksjonen tar en iterable av Story, antall som skal vises, bredde og høyde på bilde.
`def story_list(iterable_of_stories, number, thumbnail_width, thumbnail_height):`

**Comment by Haakenlid** [comment]
Listevisning for søk ser sånn ut nå:
![image](https://cloud.githubusercontent.com/assets/1686266/6476241/d04309cc-c213-11e4-9042-ebbfb9e17381.png)

Her brukes tittel og ingress, men det funker jo ikke så bra for saker uten ingress. Finn ut hvordan det kan løses på en visuell fin måte.

**Comment by Haakenlid** [comment]
Her er noen fine fra nytimes.com

![image](https://cloud.githubusercontent.com/assets/1686266/6486747/4d55c688-c28d-11e4-88ae-56de56ecf42a.png)  ![image](https://cloud.githubusercontent.com/assets/1686266/6486706/03c23dee-c28d-11e4-9a78-be53f1ed2093.png)

![image](https://cloud.githubusercontent.com/assets/1686266/6486763/72c92bd0-c28d-11e4-9055-234a28510b72.png)

![image](https://cloud.githubusercontent.com/assets/1686266/6486817/d1724b3a-c28d-11e4-8ca2-acf4bf7bf943.png)

![image](https://cloud.githubusercontent.com/assets/1686266/6486780/884520a4-c28d-11e4-86f7-45759d0651a9.png)

**Comment by Haakenlid** [comment]
The Guardian. Litt masete, men jeg liker den.

![image](https://cloud.githubusercontent.com/assets/1686266/6487798/998185aa-c293-11e4-8f14-f89616f3c02d.png)
