### ISSUE TITLE
Testing og tilpassing av css på mobil / liten skjerm

### ISSUE THREAD

**Issue by haakenlid** [universitas/universitas.no#44]
Noen greier funker ikke så bra på liten skjerm. 

Megamenyen blir skvisa.

Artikkel sidebar venstre skal legge seg horisontal.

Artikler på forsiden stabler seg på en dårlig måte på liten skjerm.

**Comment by Haakenlid** [comment]
Har endra forside-visninga for mobil, så saker og bilder legger seg mye ryddigere. 

Toppmenyen må fikses på for å bli mobil-tilpasset.
