### ISSUE TITLE
Farger

### ISSUE THREAD

**Issue by haakenlid** [universitas/universitas.no#46]
Kanskje bruke litt friskere farger? Her er en bra inspirasjon. Googles «Material Design» – den store design-dilla om dagen. http://www.google.com/design/spec/style/color.html#color-color-palette
## ![image](https://cloud.githubusercontent.com/assets/1686266/6455759/d223088e-c158-11e4-95b4-28dc95138185.png)

Fargene som er valgt nå er ut fra de opprinnelige fargene i designet for papiravisa. De er valgt ut fra hva som funker på trykk med CMYK og avispapir. Fargene er blassere enn hva man kan få til på en skjerm. 
## ![image](https://cloud.githubusercontent.com/assets/1686266/6455782/484cb4c4-c159-11e4-9369-7b3c006b3224.png)

En ulempe i øyeblikket er at det er kraftige google-vibber over å bruke rød, grønn, blå(aktig) og gul.

![image](https://cloud.githubusercontent.com/assets/1686266/6455840/f161e23c-c159-11e4-8b2b-dfd2adae5cfd.png)

**Comment by Haakenlid** [comment]
Noen eksperimenter
![megameny](https://cloud.githubusercontent.com/assets/1686266/6516636/e4154ccc-c393-11e4-8fc8-29e2c5634693.png)
