### ISSUE TITLE
Endringer i drop down-meny

### ISSUE THREAD

**Issue by geirmolnes** [universitas/universitas.no#50]
Jeg og Petter foreslår to endringer i toppmenyen:
1. Navn på kategorier bør være statisk. Fargekoden i toppen er ikke selvforklarende nok. Det er også et problem at man havner i en annen kategori når man muser over f.eks. ide og debatt, fordi kategoriene ekspanderer. 
2. Vi foreslår svart som farge på banneret, med Universitas i rød logo.

**Comment by Haakenlid** [comment]
> man havner i en annen kategori når man muser over f.eks. ide og debatt, fordi kategoriene ekspanderer. 

Det skal jeg prøve å unngå når jeg gjør ferdig menyen.
