### ISSUE TITLE
Søketreffene på nettsida bør være kronologiske

### ISSUE THREAD

**Issue by PetterFlottum** [universitas/universitas.no#58]
Treffene i søkefunksjonen bør være kronologiske med de nyeste øverst.

**Comment by Haakenlid** [comment]
Vektingen skal være basert på relevanse nå. 

Men det skal være mulig å finpusse sorteringskriteriet for søketreff. Det beste er nok å bruke en kombinasjon av relevanse (søkeordet finnes i sakens tittel/ingress og/eller nevnt flere ganger i brødtekst) og aktualitet (nye saker).

Søking er ganske kompliserte greier, og løsningen som er der nå har jeg ikke gjort så veldig mye finjustering på. Se issue #40 for fler detaljer. 

Foreløpig setter jeg dette på "lav prioritet" fordi jeg er litt usikker på hvor mye jobb som må til for å gjøre det bedre. 

Har du eksempel på et søk der sorteringen ble spesielt ugunstig?
